# Generates .sops.yaml from the keys defined in keys/default.nix,
# keys/generated/recipients.json (per-user age keys from GitHub), and
# keys/team/ (manually added team keys).
#
# Usage:
#   just rekey
#
# This produces .sops.yaml with a single catch-all creation rule that
# encrypts to every admin age key, every host age key, and every
# team member's age keys.
let
  keys = import ./keys/default.nix;

  # Per-user age keys generated by `just gen recipients`.
  # The JSON is an object keyed by username, with each value a list of age keys.
  generatedFile = ./keys/generated/recipients.json;
  generated =
    if builtins.pathExists generatedFile then
      builtins.fromJSON (builtins.readFile generatedFile)
    else
      { };

  # Manually added team keys (one age key per .pub file)
  teamDir = ./keys/team;
  teamAgeKeys =
    if builtins.pathExists teamDir then
      let
        entries = builtins.readDir teamDir;
        pubFiles = builtins.filterAttrs (
          _name: type: type == "regular" && builtins.match ".*\\.pub" _name != null
        ) entries;
      in
      builtins.mapAttrs (
        _name: _type:
        let
          content = builtins.readFile (teamDir + "/${_name}");
        in
        builtins.replaceStrings [ "\n" ] [ "" ] content
      ) pubFiles
    else
      { };

  # Flatten all generated per-user keys into one list
  generatedAgeKeys = builtins.concatLists (builtins.attrValues generated);

  # Flatten team keys into a list
  teamAgeKeysList = builtins.attrValues teamAgeKeys;

  # All host age keys
  hostAgeKeysList = builtins.attrValues keys.hostAgeKeys;

  # Every recipient that should have access to all secrets
  allRecipients = keys.adminAgeKeys ++ generatedAgeKeys ++ teamAgeKeysList ++ hostAgeKeysList;

  # Build .sops.yaml content
  # sops accepts plain key lists in creation_rules — anchors are optional.
  yaml =
    let
      indent = map (k: "      - ${k}") allRecipients;
      keysList = builtins.concatStringsSep "\n" indent;
    in
    ''
      creation_rules:
        - path_regex: .*
          age:
      ${keysList}
    '';
in
{
  inherit yaml;
}
