# Agenix rekey GitHub Actions workflow module (flake-parts)
# Automatically rekeys secrets when secrets.nix changes
#
# This is a flake-parts module that provides the workflow as a package
# that can be installed to .github/workflows/.
#
# Usage:
#   imports = [ inputs.darkmatter.flakeModules.agenix-rekey ];
#   perSystem = { ... }: {
#     darkmatter.ci.agenix-rekey.enable = true;
#   };
#
#   Then run: nix build .#agenix-rekey-workflow
#   Or use the install script: nix run .#install-agenix-rekey-workflow
#
{
  lib,
  flake-parts-lib,
  ...
}:
let
  inherit (lib) mkOption mkEnableOption types;
  inherit (flake-parts-lib) mkPerSystemOption;
in
{
  options.perSystem = mkPerSystemOption (
    {
      pkgs,
      config,
      ...
    }:
    let
      cfg = config.darkmatter.ci.agenix-rekey;

      yaml = pkgs.formats.yaml { };

      workflow = {
        name = "Rekey Agenix Secrets";

        on = {
          push = {
            branches = cfg.branches;
            paths = cfg.triggerPaths;
          };
          workflow_dispatch = { };
        };

        permissions = {
          contents = "write";
        };

        jobs = {
          rekey = {
            runs-on = cfg.runsOn;
            steps = [
              {
                name = "Checkout";
                uses = "actions/checkout@v4";
              }
              {
                name = "Install Nix";
                uses = "cachix/install-nix-action@v30";
                "with" = {
                  github_access_token = "\${{ secrets.GITHUB_TOKEN }}";
                };
              }
            ]
            ++ lib.optional cfg.cachix.enable {
              name = "Setup Cachix";
              uses = "cachix/cachix-action@v15";
              "with" = {
                name = cfg.cachix.name;
                authToken = "\${{ secrets.${cfg.cachix.authTokenSecret} }}";
              };
            }
            ++ [
              {
                name = "Setup SSH key for agenix";
                run = "mkdir -p ~/.ssh && echo \"\${{ secrets.${cfg.sshKeySecret} }}\" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519";
              }
              {
                name = "Install agenix";
                run = "nix profile install github:ryantm/agenix";
              }
              {
                name = "Rekey secrets";
                run = "cd ${cfg.secretsDir} && agenix -r";
              }
              {
                name = "Commit and push changes";
                run = lib.concatStringsSep " && " [
                  ''git config user.name "github-actions[bot]"''
                  ''git config user.email "github-actions[bot]@users.noreply.github.com"''
                  ''git diff --quiet ${cfg.secretsDir}/*.age || (git add ${cfg.secretsDir}/*.age && git commit -m "chore(secrets): rekey agenix secrets" && git push)''
                ];
              }
            ];
          };
        };
      };

      workflowFile = pkgs.runCommand "agenix-rekey.yaml" { } ''
        {
          echo '# Generated by darkmatter flake - do not edit manually'
          cat ${yaml.generate "agenix-rekey.yaml" workflow}
        } > $out
      '';

      installScript = pkgs.writeShellScriptBin "install-agenix-rekey-workflow" ''
        mkdir -p .github/workflows
        cp ${workflowFile} .github/workflows/${cfg.outputFileName}
        echo "Installed workflow to .github/workflows/${cfg.outputFileName}"
      '';
    in
    {
      options.darkmatter.ci.agenix-rekey = {
        enable = mkEnableOption "GitHub Actions workflow for automatic agenix rekeying";

        branches = mkOption {
          type = types.listOf types.str;
          default = [ "main" ];
          description = "Branches to trigger rekey on";
        };

        triggerPaths = mkOption {
          type = types.listOf types.str;
          default = [ "secrets/secrets.nix" ];
          description = "Paths that trigger the rekey workflow";
        };

        secretsDir = mkOption {
          type = types.str;
          default = "secrets";
          description = "Directory containing the secrets";
        };

        runsOn = mkOption {
          type = types.str;
          default = "ubuntu-latest";
          description = "GitHub Actions runner to use";
        };

        sshKeySecret = mkOption {
          type = types.str;
          default = "AGENIX_SSH_KEY";
          description = "Name of the GitHub secret containing the CI SSH private key";
        };

        cachix = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Enable Cachix caching in the workflow";
          };

          name = mkOption {
            type = types.str;
            default = "";
            description = "Cachix cache name";
          };

          authTokenSecret = mkOption {
            type = types.str;
            default = "CACHIX_AUTH_TOKEN";
            description = "Name of the GitHub secret containing the Cachix auth token";
          };
        };

        outputFileName = mkOption {
          type = types.str;
          default = "agenix-rekey.yaml";
          description = "Filename for the generated workflow";
        };
      };

      config = lib.mkIf cfg.enable {
        packages.agenix-rekey-workflow = workflowFile;
        apps.install-agenix-rekey-workflow = {
          type = "app";
          program = "${installScript}/bin/install-agenix-rekey-workflow";
        };
      };
    }
  );
}
